# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    # MariaDB
    mariadb:
      image: mariadb:10.6
      working_dir: /application
      restart: always
      networks:
        - labnet
      volumes:
        - maria_data:/var/lib/mysql
        - ./app/pkg/databases/database.db.sql:/docker-entrypoint-initdb.d/database.sql
      environment:
        - MYSQL_ROOT_PASSWORD=Th3R00tPassw0rd
        - MYSQL_DATABASE=appdb
        - MYSQL_USER=appuser
        - MYSQL_PASSWORD=letmein
      ports:
        - "3002:3306"

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  maria_data: