# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    # MariaDB
    mariadb:
      image: mariadb:${MARIADB_VERSION}
      working_dir: /application
      restart: always
      networks:
        - labnet
      volumes:
        - maria_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  maria_data: