# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    command: ["go", "run", "main.go"]
    env_file:
      - golang.env