# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
        - labnet
    environment:
      - DB_HOST=mariadb
      - DB_USER=appuser
      - DB_PASSWORD=letmein
      - DB_NAME=appdb

networks:
  labnet:
    driver: bridge