# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    # PostgreSQL
    pgdb:
      image: postgres:${POSTGRES_VERSION}
      restart: always
      working_dir: /application
      ports: 
        - "${POSTGRES_PORT}:5432"
      networks:
        - labnet
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}      

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  pg_data: