
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
        - labnet
    environment:
      - DB_HOST=mariadb
      - DB_USER=appuser
      - DB_PASSWORD=letmein
      - DB_NAME=appdb

  mariadb:
      image: mariadb:10.6
      working_dir: /application
      restart: always
      networks:
        - labnet
      volumes:
        - maria_data:/var/lib/mysql
        - ./app/pkg/databases/database.db.sql:/docker-entrypoint-initdb.d/database.sql
      environment:
        - MYSQL_ROOT_PASSWORD=Th3R00tPassw0rd
        - MYSQL_DATABASE=appdb
        - MYSQL_USER=appuser
        - MYSQL_PASSWORD=letmein
      ports:
        - "3002:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  maria_data:

networks:
  labnet:
    driver: bridge